# Site settings
title: Franzi's page
subtitle: "The horse party site of Iceland."
email: franzihorseparty@gmail.com
name: Franziska Kopf
description: >
  This is the best horse party site of Iceland.
  We even have Snaefellshorses.
url: "http://fancyfranz.github.io"
cover: "/images/cover.jpg"
logo: "/images/logo.png"
icon: "/images/icon.png"
front_page_news: 5
permalink: /:categories/:title/
markdown: kramdown
inter_post_navigation: true

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Disqus comments
# disqus_shortname: none

# Social icons and sharing options
social:
  - name: Twitter
    icon: twitter
    username: Franziauftwitter
    url: https://twitter.com/Franziauftwitter
    desc: Follow me on Twitter
    share: true

  - name: Facebook
    icon: facebook
    username: Franziauffacebook
    url: https://twitter.com/Franziauffacebook
    desc: Friend me on Facebook
    share: true

  - name: Google+
    icon: google-plus
    username:
    url:
    desc: Add me to your Circles
    share: false

  - name: YouTube
    icon: youtube
    username:
    url:
    desc: Subscribe on YouTube
    share: false

  - name: Instagram
    icon: instagram
    username:
    url:
    desc: Follow me on Instagram
    share: false

# Ruby gems (plugins)
gems:
  - jekyll-sitemap
