# Site settings
title:
  en: Franzi's page
  de: Franzi's Seite
  is: Franzi Isi
subtitle:
  en: "The horse party site of Iceland."
  de: "Die Pferdepartieseite von Island."
  is: "Someoldladies gothere!"
email: franzihorseparty@gmail.com
name: Franziska Kopf
description:
  en: "This is the best horse party site of Iceland. We even have Snaefellshorses."
  de: "Die beste Pferdepartieseite von Island, wir haben sogar Snafellspferde."
  is: "Someoldladies gothere all the time."
default_lang: en
url: "http://fancyfranz.github.io"
cover: "/images/cover.jpg"
logo: "/images/logo.png"
icon: "/images/icon.png"
front_page_news: 5
permalink: /:categories/:title/
markdown: kramdown
inter_post_navigation: true

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Disqus comments
# disqus_shortname: none

# Translations
sitemap:
  en: "Site Map"
  de: "&Uuml;bersicht"
  is: "Site Map"
contact:
  en: "Contact"
  de: "Kontakt"
  is: "Contactis"
subscribe:
  en: "Subscribe via RSS"
  de: "RSS"
  is: "RSS"
share:
  en: "Share"
  de: ""
  is: ""
months:
  01:
    en: "January"
    de: "Januar"
    is: "Jan"
  02:
    en: "February"
    de: "Februar"
    is: "Feb"
  03:
    en: "March"
    de: "M&auml;rz"
    is: "Mar"
  04:
    en: "April"
    de: "April"
    is: "Apr"
  05:
    en: "May"
    de: "Mai"
    is: "Mai"
  06:
    en: "June"
    de: "Juni"
    is: "Jun"
  07:
    en: "July"
    de: "Juli"
    is: "Jul"
  08:
    en: "August"
    de: "August"
    is: "Aug"
  09:
    en: "September"
    de: "September"
    is: "Sep"
  10:
    en: "Oktober"
    de: "October"
    is: "Okt"
  11:
    en: "November"
    de: "November"
    is: "Nov"
  12:
    en: "December"
    de: "Dezember"
    is: "Dec"

# Social icons and sharing options
social:
  - name: Twitter
    icon: twitter
    username: Franziauftwitter
    url: https://twitter.com/Franziauftwitter
    desc: Follow me on Twitter
    share: true

  - name: Facebook
    icon: facebook
    username: Franziauffacebook
    url: https://twitter.com/Franziauffacebook
    desc: Friend me on Facebook
    share: true

  - name: Google+
    icon: google-plus
    username:
    url:
    desc: Add me to your Circles
    share: false

  - name: YouTube
    icon: youtube
    username:
    url:
    desc: Subscribe on YouTube
    share: false

  - name: Instagram
    icon: instagram
    username:
    url:
    desc: Follow me on Instagram
    share: false

# Ruby gems (plugins)
gems:
  - jekyll-sitemap
